name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['12.x']

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: npm install & deploy
      run: |
        remote_repo="https://${secrets.GITHUB_TOKEN}@github.com/${secrets.GITHUB_REPOSITORY}.git"
        remote_branch="gh-pages"
        git config --global user.email "stef.kors@gmail.com"
        git config --global user.name "StefKors"
        npm install
        npm run deploy
      env:
        CI: true
       
